#!/usr/bin/env python3
# governance_generator.py
from datetime import datetime
import json

COMMON_BOTS = [
    ("GPTBot", "OpenAI GPTBot"),
    ("Google-Extended", "Google Extended (Gemini crawler)"),
    ("ClaudeBot", "Anthropic ClaudeBot"),
    ("PerplexityBot", "PerplexityBot"),
    ("Meta-ExternalAgent", "Meta ExternalAgent"),
    ("Grok-Bot", "xAI Grok-Bot"),
]
DEFAULT_BLOCK = [b[0] for b in COMMON_BOTS if b[0] != "Google-Extended"]


def render_robots(block_list):
    lines = [
        "# robots.txt generated by governance_generator.py",
        "# Warning: robots.txt is a voluntary directive; not a security boundary.",
        "",
    ]
    for ua in block_list:
        lines += [f"User-agent: {ua}", "Disallow: /", ""]
    lines += ["User-agent: *", "Allow: /"]
    return "\n".join(lines)


def render_llms(policy):
    human = ["# llms.txt experimental policy", ""]
    human.append("Policy summary:")
    human.append(
        policy.get("summary", "Default: allow public crawling; respect copyrights.")
    )
    human.append("")
    human.append("# Machine-readable JSON")
    human.append(json.dumps(policy, indent=2, ensure_ascii=False))
    return "\n".join(human)


def write_files(
    block_list=None, robots_out="example_robots.txt", llms_out="example_llms.txt"
):
    if block_list is None:
        block_list = DEFAULT_BLOCK
    with open(robots_out, "w", encoding="utf-8") as f:
        f.write(render_robots(block_list))
    policy = {
        "summary": "Generated via governance_generator.py",
        "blocked": block_list,
        "generated_at": datetime.utcnow().isoformat(),
    }
    with open(llms_out, "w", encoding="utf-8") as f:
        f.write(render_llms(policy))
    return robots_out, llms_out


if __name__ == "__main__":
    write_files()
    print("Wrote example_robots.txt and example_llms.txt")
